### ISSUE TITLE
Textures are not loading.

### ISSUE THREAD

**Issue by AligatorAsteroid** [gr8pefish/PortableCrafting#1]
I don't have textures for blueprints and for crafting core. I use 1.8.9 version.

**Comment by gr8pefish** [comment]
What version of forge are you using?

**Comment by AligatorAsteroid** [comment]
Latest 11.15.0.1709

**Comment by gr8pefish** [comment]
Hmm, that is very strange, nobody else is having this issue. Are you using a resource/texture pack?

**Comment by NerdMcBoon** [comment]
I'm having the very same issue.
To proivde some more info:

The crafting core and the blueprints are missing their textures, and are showing a pink cube instead.

Also, when searching for the crafting core or the blueprints in JEI, they don't show up, but when clicking on them in the recipe for the portable crafter, the recipes for them are properly shown.

![2016-01-19_17 01 15](https://cloud.githubusercontent.com/assets/16770970/12424107/f8932c1e-bece-11e5-9e2d-81241377b255.png)

Notice how I'm searching for "bluep", but nothing is found.

![2016-01-19_17 01 27](https://cloud.githubusercontent.com/assets/16770970/12424187/3df3c304-becf-11e5-95ab-300cd6684e1d.png)

After clicking on the blueprint in the crafting recipe of the portable crafter, the recipe for the blueprint  shows up.

I'm using Minecraft 1.8.9 with Forge 1.8.9 - 11.15.0.1708 and JEI 1.8.9 - 2.19.0.93, but the issue definitely already existed on older versions of Forge and JEI.

I hope this helps!

**Comment by gr8pefish** [comment]
Righty-o, I will look into this and try and get a fix out.

**Comment by gr8pefish** [comment]
Is anything appearing in your log/console?

It would likely be something while loading where it says: Unable to find model for portablecrafting:blueprint (I forget the exact syntax, but hopefully that helps).

**Comment by NerdMcBoon** [comment]
I quickly created a new launcher profile with just Portable Crafting and JEI installed, started the game, had a look at the recipes in JEI and closed the game again, so the log isn't such a convoluted mess and possible conflicts with other mods can be avoided.

There doesn't seem to be anything interesting in the log, but I'll attach it anyway.

[PortableCraftingTextureBug.txt](https://github.com/gr8pefish/PortableCrafting/files/96982/PortableCraftingTextureBug.txt)

**Comment by gr8pefish** [comment]
Hmm that is strange indeed. 

Are you using java 8?
So I can replicate it, you just started up a new game with PortableCrafting and JEI and you got the missing texture error?

**Comment by NerdMcBoon** [comment]
Yes, exactly.

I'm using the 64 bit version of Java 8.

**Comment by gr8pefish** [comment]
Okay I found it, it was one lowercase letter in the json filename that should have been capitalized! So strange that it wasn't showing up in my dev environment, I have no idea why that was. Anyways, a fix will be up momentarily.

**Comment by NerdMcBoon** [comment]
Nice! It's always the stupid little mistakes!

I'm glad you could fix it!

**Comment by gr8pefish** [comment]
Just look for v1.1 on curseforge, it is uploaded and just waiting for approval. Enjoy!
